version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 622806142749.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=622806142749.dkr.ecr.us-east-1.amazonaws.com/cyderes-docker-repo-ecr
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPO_URI:$IMAGE_TAG .
      - docker tag $REPO_URI:$IMAGE_TAG $REPO_URI:latest  # Add 'latest' tag
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPO_URI:$IMAGE_TAG
      - docker push $REPO_URI:latest                      # Push 'latest' tag
      - echo Writing image definitions...
      - printf '[{"name":"cyderes-docker-repo-ecr","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: 
    - imagedefinitions.json
